# Site
repository: laoman/laoman.github.io
# favicon: images/favicon.ico

# Personal info
name: Georgios Georgiou 
title: Lead Software Developer
email: indefixx@email.co.uk
website: www.github.com/laoman/laoman.github.io

# Social links
twitter_username: laoman
github_username:  laoman
# dribbble_username: jekyll
 facebook_username: georgios.georgiou
flickr_username: laoman
instagram_username: laoman
linkedin_username: georgiosgeorgiou
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  Hi, my name is Georgios Georgiou and i am a Software Developer for the electronic payments industry, technology addict, developer by day developer by night!

  I am most skilled in: <mark>Oracle</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Photography
   - Gaming
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
